name: Deploy To-Do App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip postgresql postgresql-contrib nginx

      - name: Start postgresql instance
        run:  sudo systemctl start postgresql  
        
      - name: Pause for init postgresql instance and check postgresql instance
        run:  sleep 7 && pg_lsclusters
      
      - name: Set up PostgreSQL
        run: |
          sudo -u postgres psql -c "CREATE DATABASE todolist;"
          sudo -u postgres psql -c "CREATE USER todouser WITH PASSWORD 'password';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE todolist TO todouser;"

      - name: Pull files from git
        run:  git pull origin master 

      - name: Install python requiriments
        run: pip install -r requirements.txt

      - name: Configure nginx and init changes
        run: |
          sudo cp ./config/nginx/todoapp /etc/nginx/sites-enabled/
          sudo systemctl restart nginx
      
      - name: Start app
        run: python3 app.py &

      - name: Check throw serveo
        run: ssh -R 80:localhost:80 serveo.net

      # - name: Check work (html)
      #   run: curl localhost:80 

      # - name: Get SSH  
      #   uses: mxschmitt/action-tmate@v3
      
