name: Deploy To-Do App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip postgresql postgresql-contrib nginx

      - name: Start postgresql instance
        run:  sudo systemctl start postgresql  
        
      - name: Pause for init postgresql instance and check postgresql instance
        run:  sleep 7 && pg_lsclusters

      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
      
      - name: Set up PostgreSQL
        run: |
          sudo -u postgres psql -c "CREATE DATABASE todolist;"
          sudo -u postgres psql -c "CREATE USER todouser WITH PASSWORD 'password';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE todolist TO todouser;"

      - name: Pull files from git
          git pull origin master

      - name: Install python requiriments
          pip install -r requirement.txt

      - name: Configure nginx and init changes
        run: |
          sudo cp ~/config/nginx/todoapp /etc/nginx/sites-enabled/
          # sudo ln -s /etc/nginx/sites-available/todoapp /etc/nginx/sites-enabled/
          sudo systemctl restart nginx

      - name: Start app
        run: |
          # sudo su
          # mkdir ~/todoapp
          # cd ~/todoapp
          # git pull origin master
          # pip install -r requirements.txt
          # sudo systemctl restart nginx
           nohup python3 app.py > app.log 2>&1 &

      - name: Get SSH  
        uses: mxschmitt/action-tmate@v3
