name: Deploy To-Do App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip postgresql postgresql-contrib nginx

      - name: Set up PostgreSQL
        run: |
          sudo -u postgres psql -c "CREATE DATABASE todolist;"
          sudo -u postgres psql -c "CREATE USER todouser WITH PASSWORD 'password';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE todolist TO todouser;"

      - name: Deploy application
        run: |
          cd ~/todoapp
          git pull origin master
          pip install -r requirements.txt
          sudo systemctl restart nginx
          nohup python3 app.py > app.log 2>&1 &
